### PR TITLE
User metadata added

### PR DESCRIPTION
**Pull request by hurelhuyag**
Maybe metadata is useless. But I need type for determine user is profile or page.

### CODE REVIEW

**Comment by roundrop** [comment]
Compilation error occured.  Cause of it is Log4j2 requires Java7 or greater.
I can't accept Log4j2 support because Facebook4J must support Java5.

And this PR is difficult to merge, because included 2 features in 1 pull-request.

Thanks,

**Comment by hurelhuyag** [comment]
Sorry I have no enough knowledge about pull request. I added one feature after pull request. But I think Log4j2 is optional feature here. We can keep support Java5. We just need to update compiler version.

**Comment by roundrop** [comment]
I don't think accepting Log4J2 support because F4J must keep compiler version 5.
But I'll accept metadata in user resource feature later.
Thanks,

**Comment by roundrop** [comment]
I've created #100 .
Thanks,

**Pull request closed without merging**
